### ISSUE TITLE
Inorrect installation

### ISSUE THREAD

**Issue by sashnv** [AmomentOfMusic/Zotero_scrivener_picker_windows#2]
Hello,

I have followed all the steps exactyl but when I press the shortcut or choose Format>Bibliography/Citation I get an error window from Scrivener telling me that "Bibiography/Citation Manager not found". I apologize for not having more concrete details but I just followed all the steps and I don't know what is wrong. I am using the latest 5.0.47 version of Zotero and Scrivener (portable) version 1.97. Any tips would be greatly appreciated.

**Comment by AmomentOfMusic** [comment]
(sorry for the delay! Only just saw this, as I apparently didn't turn on email notifications)

Alright, it looks the problem was on my end, that I didn't regenerate the .lnk file when I renamed some things. Please try downloading the folder again and see if it works.

If not, you should be able to solve the problem yourself by deleting the .lnk file in the folder and right-clicking on the batch file to create a new shortcut. Point Scrivener to this newly generate .lnk file and you should be in business.

Either way, please let me know if this resolves the issue.

**Comment by sashnv** [comment]
Hi Emilie thanks for the attentive response. 
I re-downloaded the modified folder you uploaded and now Scrivener seems to recognize the command but I get a different error message apparently related to an obstacle in initializing the Zotero call. I have attached a screen capture of the error... Any idea?

Many thanks!

![error](https://user-images.githubusercontent.com/3706558/40434925-c21482ae-5eaf-11e8-83b2-bdcf61ef9f80.jpg)

**Comment by AmomentOfMusic** [comment]
Hmm, okay.  Here are some thoughts

1. Is Zotero open? I should have included it in the readme, but Zotero needs to be in the background for it to work.

2. Are you keeping all three files in the same folder? They are all necessary to get everything is working.


If the answer to both of these is yes, then try working through the following and let me know which are/are not working.

(note that in all cases, the picker, the first time it is called up will sometimes not come to the front - you might have to call it up to the front yourself by hovering over the zotero icon on your task bar and clicking on the window - this is a Zotero bug that I have reported. After the first time you call it up, it should come to the front by itself... most of the time).

1. Right click on the powershell script, and click "run with powershell". This should call up the picker. Please make sure that this is the case. 

2. If yes, double click on the batch file. Does it still work?

3. If yes, Double-click on the link file. Is the picker still being called up?

Please let me know if at any point the picker is not called up - this should give me a slightly better idea of what is going on.

Finally, what version of Windows are you using? Do you have a x32 or x64 bit machine? This might be a compatibility issue based on what the error code is... If so, I can try to see what I can do to fix it

**Comment by sashnv** [comment]
The picker is called up in all three cases, strange... I am running Windows 10 in x64.
Maybe it is a Scrivener issue? Or a file permission one?

**Comment by AmomentOfMusic** [comment]
Huh. Those are all the same system specifications I have... so it's not a compatibility issue. 

You can test whether it is a Scrivener problem by pointing the bibliography/citation manager to any random exe file. This should open whatever application you have set it to. If you still run into the same error, then your best bet might be to post a bug report in the Scrivener forum.... I'm not sure there is much else I can do. 

My only  other thought based on this [ website](https://windowsfish.com/how-to-fix-0xc000007b-error/) is that it might be a case of not running Scrivener as an administrator. You can right click the scrivener.exe file (or any shortcut you use) and click **properties>compatibility>run as administrator.** Close Scrivener and try again.

I would finally try restarting computer, and trying to re-pointing Scrivener to the .lnk. You never know, it might fix the problem.

In the meantime, I am going to try using this script on another one of my computers to see if I have the same problem...

**Comment by AmomentOfMusic** [comment]
I've since ran this script on another computer - I didn't get the error you did, but I did run across another issue which has been fixed. I don't think this will fix your problem, but just in case, can you try the new file I've uploaded?

Let me know as well whether you are able to launch other exe files from the citation manager settings as detailed above.
