### ISSUE TITLE
Picker appearing and allowing selection but nothing is appearing in the footnote in Scrivener.

### ISSUE THREAD

**Issue by AbbiwithanI** [AmomentOfMusic/Zotero_scrivener_picker_windows#8]
Hello, I'm probably doing something really basic wrong but at the moment when I call the picker it all works (apart from the fact it isn't sitting on top) but it doesn't put in the scannable citation. I'm panicking somewhat as I've a deadline fast approaching. Help please.

**Comment by meredithmp** [comment]
I am having the same issue. I've used this successfully in the past, but recently returned to Scrivener and I find it not working anymore. Everything appears to operate smoothly, but when I hit "enter" the picker simply closes and nothing happens in Scrivener.

**Comment by GabrielleduVent** [comment]
Same here. The batch file seems to generate the citation but it does not actually transfer it to the document. 

<img width="960" alt="2022-09-22 (2)" src="https://user-images.githubusercontent.com/108250063/191797042-27ff1ea0-933a-4a7a-9637-1c368a21ae00.png">

The batch file seems to execute this, but then nothing.

**Comment by thecooldaniel** [comment]
This might only apply to Windows 11, but here is what worked for me:

For every file contained in `zotpick.zip`  **except** the shortcut file, do the following:
1. Right click the file
2. Choose "properties"
3. At the bottom of the General tab, check the "Unblock" box then click "Ok"
![image](https://user-images.githubusercontent.com/12212/232264925-56e2c61c-eb43-49c0-a675-84a821dad995.png)

Everything should work now :)

**Comment by munir-paviwala** [comment]
I had a similar issue. Even after trying what @thecooldaniel suggested, it did not work.

As a workaround, I modified the [Scrivener-picker.ps1](https://github.com/AmomentOfMusic/Zotero_scrivener_picker_windows/blob/master/Scrivener-picker.ps1) script to add the citation to the Clipboard instead of pushing it directly to Scrivener.

Now, after using the picker, I simply switch to Scrivener and press **Ctrl+V** to paste the citation. While it's a few extra keystrokes, this method works reliably for me.

Here is the modified script:

```powershell
[CmdletBinding()]
Param(
)

add-type -AssemblyName microsoft.VisualBasic
import-module $PsScriptRoot\AutoItX.psd1

# Get handle of active window (Scrivener)
$Activewindow = Get-AU3WinHandle -Title ''

# Check if Zotero is running. If not, launch the program and wait until BBT plugin is ready  
if ((get-process "zotero" -ErrorAction SilentlyContinue) -eq $Null) 
{    
    Start-Process -filepath zotero.exe -WindowStyle Minimized

    $probe = "starting"
  
    while ($probe -notmatch "ready") 
    {
        start-sleep -Seconds 1

        try 
        {
            $probe = invoke-webrequest 'http://localhost:23119/better-bibtex/cayw?probe=true' -usebasicparsing -userAgent 'USER'
            echo $probe.Content
        }

        catch 
        { 
            echo "waiting" 
        }
    }
 }
else 
{ 
    echo "Zotero is running" 
}

# Activate Zotero to ensure picker comes to the front
[Microsoft.VisualBasic.Interaction]::AppActivate((Get-Process Zotero).ID)

# Call CAYW picker
$ref = invoke-webrequest 'http://localhost:23119/better-bibtex/cayw?format=scannable-cite' -usebasicparsing -userAgent 'USER'

# Copy $ref to clipboard
[System.Windows.Forms.Clipboard]::SetText($ref.Content)

# Set Scrivener as foreground window
Show-AU3WinActivate($Activewindow)
Wait-AU3WinActive($Activewindow)

echo "Reference copied to clipboard"

# You can now manually paste the reference in Scrivener using a hotkey (e.g., Ctrl+V)
```

I'm open to any other suggestions if anyone has a more elegant solution.
